version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - 依存関係更新
    commit-message:
      prefix: "依存関係更新"
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - 依存関係更新
    commit-message:
      prefix: "依存関係更新"
    groups:
      root-npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/apps/desktop/src-tauri"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - 依存関係更新
    commit-message:
      prefix: "依存関係更新"
    groups:
      rust-minor-patch:
        update-types:
          - "minor"
          - "patch"
